// Combat slot items extracted from the simulator
// This data structure will be populated dynamically from the combat simulator
// Each slot contains items mapped by their itemHrid to their display name

export interface CombatSlotItems {
  [slot: string]: {
    [itemHrid: string]: string;
  };
}

// Complete combat items data from the combat simulator
// Contains all 327 items across 11 equipment slots
export const COMBAT_ITEMS: CombatSlotItems = {
  head: {
    "/items/red_culinary_hat": "Red Culinary Hat",
    "/items/snail_shell_helmet": "Snail Shell Helmet",
    "/items/vision_helmet": "Vision Helmet",
    "/items/fluffy_red_hat": "Fluffy Red Hat",
    "/items/corsair_helmet": "Corsair Helmet",
    "/items/corsair_helmet_refined": "Corsair Helmet (R)",
    "/items/acrobatic_hood": "Acrobatic Hood",
    "/items/acrobatic_hood_refined": "Acrobatic Hood (R)",
    "/items/magicians_hat": "Magician's Hat",
    "/items/magicians_hat_refined": "Magician's Hat (R)",
    "/items/cheese_helmet": "Cheese Helmet",
    "/items/verdant_helmet": "Verdant Helmet",
    "/items/azure_helmet": "Azure Helmet",
    "/items/burble_helmet": "Burble Helmet",
    "/items/crimson_helmet": "Crimson Helmet",
    "/items/rainbow_helmet": "Rainbow Helmet",
    "/items/holy_helmet": "Holy Helmet",
    "/items/rough_hood": "Rough Hood",
    "/items/reptile_hood": "Reptile Hood",
    "/items/gobo_hood": "Gobo Hood",
    "/items/beast_hood": "Beast Hood",
    "/items/umbral_hood": "Umbral Hood",
    "/items/cotton_hat": "Cotton Hat",
    "/items/linen_hat": "Linen Hat",
    "/items/bamboo_hat": "Bamboo Hat",
    "/items/silk_hat": "Silk Hat",
    "/items/radiant_hat": "Radiant Hat"
  },
  neck: {
    "/items/necklace_of_efficiency": "Necklace Of Efficiency",
    "/items/fighter_necklace": "Fighter Necklace",
    "/items/ranger_necklace": "Ranger Necklace",
    "/items/wizard_necklace": "Wizard Necklace",
    "/items/necklace_of_wisdom": "Necklace Of Wisdom",
    "/items/necklace_of_speed": "Necklace Of Speed",
    "/items/philosophers_necklace": "Philosopher's Necklace"
  },
  earrings: {
    "/items/earrings_of_gathering": "Earrings Of Gathering",
    "/items/earrings_of_essence_find": "Earrings Of Essence Find",
    "/items/earrings_of_armor": "Earrings Of Armor",
    "/items/earrings_of_regeneration": "Earrings Of Regeneration",
    "/items/earrings_of_resistance": "Earrings Of Resistance",
    "/items/earrings_of_rare_find": "Earrings Of Rare Find",
    "/items/earrings_of_critical_strike": "Earrings Of Critical Strike",
    "/items/philosophers_earrings": "Philosopher's Earrings"
  },
  body: {
    "/items/dairyhands_top": "Dairyhand's Top",
    "/items/foragers_top": "Forager's Top",
    "/items/lumberjacks_top": "Lumberjack's Top",
    "/items/cheesemakers_top": "Cheesemaker's Top",
    "/items/crafters_top": "Crafter's Top",
    "/items/tailors_top": "Tailor's Top",
    "/items/chefs_top": "Chef's Top",
    "/items/brewers_top": "Brewer's Top",
    "/items/alchemists_top": "Alchemist's Top",
    "/items/enhancers_top": "Enhancer's Top",
    "/items/gator_vest": "Gator Vest",
    "/items/turtle_shell_body": "Turtle Shell Body",
    "/items/colossus_plate_body": "Colossus Plate Body",
    "/items/demonic_plate_body": "Demonic Plate Body",
    "/items/anchorbound_plate_body": "Anchorbound Plate Body",
    "/items/anchorbound_plate_body_refined": "Anchorbound Plate Body (R)",
    "/items/maelstrom_plate_body": "Maelstrom Plate Body",
    "/items/maelstrom_plate_body_refined": "Maelstrom Plate Body (R)",
    "/items/marine_tunic": "Marine Tunic",
    "/items/revenant_tunic": "Revenant Tunic",
    "/items/griffin_tunic": "Griffin Tunic",
    "/items/kraken_tunic": "Kraken Tunic",
    "/items/kraken_tunic_refined": "Kraken Tunic (R)",
    "/items/icy_robe_top": "Icy Robe Top",
    "/items/flaming_robe_top": "Flaming Robe Top",
    "/items/luna_robe_top": "Luna Robe Top",
    "/items/royal_water_robe_top": "Royal Water Robe Top",
    "/items/royal_water_robe_top_refined": "Royal Water Robe Top (R)",
    "/items/royal_nature_robe_top": "Royal Nature Robe Top",
    "/items/royal_nature_robe_top_refined": "Royal Nature Robe Top (R)",
    "/items/royal_fire_robe_top": "Royal Fire Robe Top",
    "/items/royal_fire_robe_top_refined": "Royal Fire Robe Top (R)",
    "/items/cheese_plate_body": "Cheese Plate Body",
    "/items/verdant_plate_body": "Verdant Plate Body",
    "/items/azure_plate_body": "Azure Plate Body",
    "/items/burble_plate_body": "Burble Plate Body",
    "/items/crimson_plate_body": "Crimson Plate Body",
    "/items/rainbow_plate_body": "Rainbow Plate Body",
    "/items/holy_plate_body": "Holy Plate Body",
    "/items/rough_tunic": "Rough Tunic",
    "/items/reptile_tunic": "Reptile Tunic",
    "/items/gobo_tunic": "Gobo Tunic",
    "/items/beast_tunic": "Beast Tunic",
    "/items/umbral_tunic": "Umbral Tunic",
    "/items/cotton_robe_top": "Cotton Robe Top",
    "/items/linen_robe_top": "Linen Robe Top",
    "/items/bamboo_robe_top": "Bamboo Robe Top",
    "/items/silk_robe_top": "Silk Robe Top",
    "/items/radiant_robe_top": "Radiant Robe Top"
  },
  legs: {
    "/items/dairyhands_bottoms": "Dairyhand's Bottoms",
    "/items/foragers_bottoms": "Forager's Bottoms",
    "/items/lumberjacks_bottoms": "Lumberjack's Bottoms",
    "/items/cheesemakers_bottoms": "Cheesemaker's Bottoms",
    "/items/crafters_bottoms": "Crafter's Bottoms",
    "/items/tailors_bottoms": "Tailor's Bottoms",
    "/items/chefs_bottoms": "Chef's Bottoms",
    "/items/brewers_bottoms": "Brewer's Bottoms",
    "/items/alchemists_bottoms": "Alchemist's Bottoms",
    "/items/enhancers_bottoms": "Enhancer's Bottoms",
    "/items/turtle_shell_legs": "Turtle Shell Legs",
    "/items/colossus_plate_legs": "Colossus Plate Legs",
    "/items/demonic_plate_legs": "Demonic Plate Legs",
    "/items/anchorbound_plate_legs": "Anchorbound Plate Legs",
    "/items/anchorbound_plate_legs_refined": "Anchorbound Plate Legs (R)",
    "/items/maelstrom_plate_legs": "Maelstrom Plate Legs",
    "/items/maelstrom_plate_legs_refined": "Maelstrom Plate Legs (R)",
    "/items/marine_chaps": "Marine Chaps",
    "/items/revenant_chaps": "Revenant Chaps",
    "/items/griffin_chaps": "Griffin Chaps",
    "/items/kraken_chaps": "Kraken Chaps",
    "/items/kraken_chaps_refined": "Kraken Chaps (R)",
    "/items/icy_robe_bottoms": "Icy Robe Bottoms",
    "/items/flaming_robe_bottoms": "Flaming Robe Bottoms",
    "/items/luna_robe_bottoms": "Luna Robe Bottoms",
    "/items/royal_water_robe_bottoms": "Royal Water Robe Bottoms",
    "/items/royal_water_robe_bottoms_refined": "Royal Water Robe Bottoms (R)",
    "/items/royal_nature_robe_bottoms": "Royal Nature Robe Bottoms",
    "/items/royal_nature_robe_bottoms_refined": "Royal Nature Robe Bottoms (R)",
    "/items/royal_fire_robe_bottoms": "Royal Fire Robe Bottoms",
    "/items/royal_fire_robe_bottoms_refined": "Royal Fire Robe Bottoms (R)",
    "/items/cheese_plate_legs": "Cheese Plate Legs",
    "/items/verdant_plate_legs": "Verdant Plate Legs",
    "/items/azure_plate_legs": "Azure Plate Legs",
    "/items/burble_plate_legs": "Burble Plate Legs",
    "/items/crimson_plate_legs": "Crimson Plate Legs",
    "/items/rainbow_plate_legs": "Rainbow Plate Legs",
    "/items/holy_plate_legs": "Holy Plate Legs",
    "/items/rough_chaps": "Rough Chaps",
    "/items/reptile_chaps": "Reptile Chaps",
    "/items/gobo_chaps": "Gobo Chaps",
    "/items/beast_chaps": "Beast Chaps",
    "/items/umbral_chaps": "Umbral Chaps",
    "/items/cotton_robe_bottoms": "Cotton Robe Bottoms",
    "/items/linen_robe_bottoms": "Linen Robe Bottoms",
    "/items/bamboo_robe_bottoms": "Bamboo Robe Bottoms",
    "/items/silk_robe_bottoms": "Silk Robe Bottoms",
    "/items/radiant_robe_bottoms": "Radiant Robe Bottoms"
  },
  feet: {
    "/items/collectors_boots": "Collector's Boots",
    "/items/shoebill_shoes": "Shoebill Shoes",
    "/items/black_bear_shoes": "Black Bear Shoes",
    "/items/grizzly_bear_shoes": "Grizzly Bear Shoes",
    "/items/polar_bear_shoes": "Polar Bear Shoes",
    "/items/centaur_boots": "Centaur Boots",
    "/items/sorcerer_boots": "Sorcerer Boots",
    "/items/cheese_boots": "Cheese Boots",
    "/items/verdant_boots": "Verdant Boots",
    "/items/azure_boots": "Azure Boots",
    "/items/burble_boots": "Burble Boots",
    "/items/crimson_boots": "Crimson Boots",
    "/items/rainbow_boots": "Rainbow Boots",
    "/items/holy_boots": "Holy Boots",
    "/items/rough_boots": "Rough Boots",
    "/items/reptile_boots": "Reptile Boots",
    "/items/gobo_boots": "Gobo Boots",
    "/items/beast_boots": "Beast Boots",
    "/items/umbral_boots": "Umbral Boots",
    "/items/cotton_boots": "Cotton Boots",
    "/items/linen_boots": "Linen Boots",
    "/items/bamboo_boots": "Bamboo Boots",
    "/items/silk_boots": "Silk Boots",
    "/items/radiant_boots": "Radiant Boots"
  },
  hands: {
    "/items/enchanted_gloves": "Enchanted Gloves",
    "/items/pincer_gloves": "Pincer Gloves",
    "/items/panda_gloves": "Panda Gloves",
    "/items/magnetic_gloves": "Magnetic Gloves",
    "/items/dodocamel_gauntlets": "Dodocamel Gauntlets",
    "/items/dodocamel_gauntlets_refined": "Dodocamel Gauntlets (R)",
    "/items/sighted_bracers": "Sighted Bracers",
    "/items/marksman_bracers": "Marksman Bracers",
    "/items/marksman_bracers_refined": "Marksman Bracers (R)",
    "/items/chrono_gloves": "Chrono Gloves",
    "/items/cheese_gauntlets": "Cheese Gauntlets",
    "/items/verdant_gauntlets": "Verdant Gauntlets",
    "/items/azure_gauntlets": "Azure Gauntlets",
    "/items/burble_gauntlets": "Burble Gauntlets",
    "/items/crimson_gauntlets": "Crimson Gauntlets",
    "/items/rainbow_gauntlets": "Rainbow Gauntlets",
    "/items/holy_gauntlets": "Holy Gauntlets",
    "/items/rough_bracers": "Rough Bracers",
    "/items/reptile_bracers": "Reptile Bracers",
    "/items/gobo_bracers": "Gobo Bracers",
    "/items/beast_bracers": "Beast Bracers",
    "/items/umbral_bracers": "Umbral Bracers",
    "/items/cotton_gloves": "Cotton Gloves",
    "/items/linen_gloves": "Linen Gloves",
    "/items/bamboo_gloves": "Bamboo Gloves",
    "/items/silk_gloves": "Silk Gloves",
    "/items/radiant_gloves": "Radiant Gloves"
  },
  ring: {
    "/items/ring_of_gathering": "Ring Of Gathering",
    "/items/ring_of_essence_find": "Ring Of Essence Find",
    "/items/ring_of_armor": "Ring Of Armor",
    "/items/ring_of_regeneration": "Ring Of Regeneration",
    "/items/ring_of_resistance": "Ring Of Resistance",
    "/items/ring_of_rare_find": "Ring Of Rare Find",
    "/items/ring_of_critical_strike": "Ring Of Critical Strike",
    "/items/philosophers_ring": "Philosopher's Ring"
  },
  weapon: {
    "/items/stalactite_spear": "Stalactite Spear",
    "/items/granite_bludgeon": "Granite Bludgeon",
    "/items/furious_spear": "Furious Spear",
    "/items/furious_spear_refined": "Furious Spear (R)",
    "/items/regal_sword": "Regal Sword",
    "/items/regal_sword_refined": "Regal Sword (R)",
    "/items/chaotic_flail": "Chaotic Flail",
    "/items/chaotic_flail_refined": "Chaotic Flail (R)",
    "/items/soul_hunter_crossbow": "Soul Hunter Crossbow",
    "/items/sundering_crossbow": "Sundering Crossbow",
    "/items/sundering_crossbow_refined": "Sundering Crossbow (R)",
    "/items/frost_staff": "Frost Staff",
    "/items/infernal_battlestaff": "Infernal Battlestaff",
    "/items/jackalope_staff": "Jackalope Staff",
    "/items/rippling_trident": "Rippling Trident",
    "/items/rippling_trident_refined": "Rippling Trident (R)",
    "/items/blooming_trident": "Blooming Trident",
    "/items/blooming_trident_refined": "Blooming Trident (R)",
    "/items/blazing_trident": "Blazing Trident",
    "/items/blazing_trident_refined": "Blazing Trident (R)",
    "/items/cheese_sword": "Cheese Sword",
    "/items/verdant_sword": "Verdant Sword",
    "/items/azure_sword": "Azure Sword",
    "/items/burble_sword": "Burble Sword",
    "/items/crimson_sword": "Crimson Sword",
    "/items/rainbow_sword": "Rainbow Sword",
    "/items/holy_sword": "Holy Sword",
    "/items/cheese_spear": "Cheese Spear",
    "/items/verdant_spear": "Verdant Spear",
    "/items/azure_spear": "Azure Spear",
    "/items/burble_spear": "Burble Spear",
    "/items/crimson_spear": "Crimson Spear",
    "/items/rainbow_spear": "Rainbow Spear",
    "/items/holy_spear": "Holy Spear",
    "/items/cheese_mace": "Cheese Mace",
    "/items/verdant_mace": "Verdant Mace",
    "/items/azure_mace": "Azure Mace",
    "/items/burble_mace": "Burble Mace",
    "/items/crimson_mace": "Crimson Mace",
    "/items/rainbow_mace": "Rainbow Mace",
    "/items/holy_mace": "Holy Mace",
    "/items/wooden_crossbow": "Wooden Crossbow",
    "/items/birch_crossbow": "Birch Crossbow",
    "/items/cedar_crossbow": "Cedar Crossbow",
    "/items/purpleheart_crossbow": "Purpleheart Crossbow",
    "/items/ginkgo_crossbow": "Ginkgo Crossbow",
    "/items/redwood_crossbow": "Redwood Crossbow",
    "/items/arcane_crossbow": "Arcane Crossbow",
    "/items/wooden_water_staff": "Wooden Water Staff",
    "/items/birch_water_staff": "Birch Water Staff",
    "/items/cedar_water_staff": "Cedar Water Staff",
    "/items/purpleheart_water_staff": "Purpleheart Water Staff",
    "/items/ginkgo_water_staff": "Ginkgo Water Staff",
    "/items/redwood_water_staff": "Redwood Water Staff",
    "/items/arcane_water_staff": "Arcane Water Staff",
    "/items/wooden_nature_staff": "Wooden Nature Staff",
    "/items/birch_nature_staff": "Birch Nature Staff",
    "/items/cedar_nature_staff": "Cedar Nature Staff",
    "/items/purpleheart_nature_staff": "Purpleheart Nature Staff",
    "/items/ginkgo_nature_staff": "Ginkgo Nature Staff",
    "/items/redwood_nature_staff": "Redwood Nature Staff",
    "/items/arcane_nature_staff": "Arcane Nature Staff",
    "/items/wooden_fire_staff": "Wooden Fire Staff",
    "/items/birch_fire_staff": "Birch Fire Staff",
    "/items/cedar_fire_staff": "Cedar Fire Staff",
    "/items/purpleheart_fire_staff": "Purpleheart Fire Staff",
    "/items/ginkgo_fire_staff": "Ginkgo Fire Staff",
    "/items/redwood_fire_staff": "Redwood Fire Staff",
    "/items/arcane_fire_staff": "Arcane Fire Staff",
    "/items/gobo_stabber": "Gobo Stabber",
    "/items/gobo_slasher": "Gobo Slasher",
    "/items/gobo_smasher": "Gobo Smasher",
    "/items/spiked_bulwark": "Spiked Bulwark",
    "/items/werewolf_slasher": "Werewolf Slasher",
    "/items/griffin_bulwark": "Griffin Bulwark",
    "/items/griffin_bulwark_refined": "Griffin Bulwark (R)",
    "/items/gobo_shooter": "Gobo Shooter",
    "/items/vampiric_bow": "Vampiric Bow",
    "/items/cursed_bow": "Cursed Bow",
    "/items/cursed_bow_refined": "Cursed Bow (R)",
    "/items/gobo_boomstick": "Gobo Boomstick",
    "/items/cheese_bulwark": "Cheese Bulwark",
    "/items/verdant_bulwark": "Verdant Bulwark",
    "/items/azure_bulwark": "Azure Bulwark",
    "/items/burble_bulwark": "Burble Bulwark",
    "/items/crimson_bulwark": "Crimson Bulwark",
    "/items/rainbow_bulwark": "Rainbow Bulwark",
    "/items/holy_bulwark": "Holy Bulwark",
    "/items/wooden_bow": "Wooden Bow",
    "/items/birch_bow": "Birch Bow",
    "/items/cedar_bow": "Cedar Bow",
    "/items/purpleheart_bow": "Purpleheart Bow",
    "/items/ginkgo_bow": "Ginkgo Bow",
    "/items/redwood_bow": "Redwood Bow",
    "/items/arcane_bow": "Arcane Bow"
  },
  off_hand: {
    "/items/eye_watch": "Eye Watch",
    "/items/snake_fang_dirk": "Snake Fang Dirk",
    "/items/vision_shield": "Vision Shield",
    "/items/gobo_defender": "Gobo Defender",
    "/items/vampire_fang_dirk": "Vampire Fang Dirk",
    "/items/knights_aegis": "Knight's Aegis",
    "/items/knights_aegis_refined": "Knight's Aegis (R)",
    "/items/treant_shield": "Treant Shield",
    "/items/manticore_shield": "Manticore Shield",
    "/items/tome_of_healing": "Tome Of Healing",
    "/items/tome_of_the_elements": "Tome Of The Elements",
    "/items/watchful_relic": "Watchful Relic",
    "/items/bishops_codex": "Bishop's Codex",
    "/items/bishops_codex_refined": "Bishop's Codex (R)",
    "/items/cheese_buckler": "Cheese Buckler",
    "/items/verdant_buckler": "Verdant Buckler",
    "/items/azure_buckler": "Azure Buckler",
    "/items/burble_buckler": "Burble Buckler",
    "/items/crimson_buckler": "Crimson Buckler",
    "/items/rainbow_buckler": "Rainbow Buckler",
    "/items/holy_buckler": "Holy Buckler",
    "/items/wooden_shield": "Wooden Shield",
    "/items/birch_shield": "Birch Shield",
    "/items/cedar_shield": "Cedar Shield",
    "/items/purpleheart_shield": "Purpleheart Shield",
    "/items/ginkgo_shield": "Ginkgo Shield",
    "/items/redwood_shield": "Redwood Shield",
    "/items/arcane_shield": "Arcane Shield"
  },
  pouch: {
    "/items/small_pouch": "Small Pouch",
    "/items/medium_pouch": "Medium Pouch",
    "/items/large_pouch": "Large Pouch",
    "/items/giant_pouch": "Giant Pouch",
    "/items/gluttonous_pouch": "Gluttonous Pouch",
    "/items/guzzling_pouch": "Guzzling Pouch"
  }
};

// Combat equipment slots
export const COMBAT_SLOTS = [
  'head', 'neck', 'earrings', 'body', 'legs', 'feet', 'hands',
  'ring', 'weapon', 'off_hand', 'pouch'
] as const;

export type CombatSlot = typeof COMBAT_SLOTS[number];

// Utility function to get all items for a specific slot
export function getItemsForSlot(combatItems: CombatSlotItems, slot: CombatSlot): { value: string; label: string }[] {
  const slotItems = combatItems[slot] || {};
  return Object.entries(slotItems).map(([itemHrid, itemName]) => ({
    value: itemHrid,
    label: itemName
  }));
}

// Utility function to get item name by HRID
export function getItemName(combatItems: CombatSlotItems, slot: CombatSlot, itemHrid: string): string {
  return combatItems[slot]?.[itemHrid] || itemHrid;
}